version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-30
    working_directory: ~/project

jobs:
  build:
    executor: android-executor
    steps:
      - checkout

      # Install Java 17
      - run:
          name: Install JDK 17
          command: |
            sudo apt-get update
            sudo apt-get install openjdk-17-jdk -y
            sudo update-alternatives --config java

      # Verify Java 17 is installed
      - run:
          name: Verify Java Version
          command: java -version

      # Set executable permissions for gradlew
      - run:
          name: Set executable permission for gradlew
          command: chmod +x ./gradlew

      # Download project dependencies
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies

      # Build the APK
      - run:
          name: Build APK
          command: ./gradlew assembleDebug

      # Store the APK as an artifact
      - store_artifacts:
          path: app/build/outputs/apk/debug/app-debug.apk
          destination: app-debug.apk

  test:
    executor: android-executor
    steps:
      - checkout

      # Install Java 17
      - run:
          name: Install JDK 17
          command: |
            sudo apt-get update
            sudo apt-get install openjdk-17-jdk -y
            sudo update-alternatives --config java

      # Verify Java 17 is installed
      - run:
          name: Verify Java Version
          command: java -version

      # Set executable permissions for gradlew
      - run:
          name: Set executable permission for gradlew
          command: chmod +x ./gradlew

      # Run unit tests
      - run:
          name: Run Unit Tests
          command: ./gradlew testDebug

      # Store test results
      - store_test_results:
          path: app/build/test-results/testDebugUnitTest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
